%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook:
%    /home/kilian/Dropbox/Teaching/introductiontoeconometricsoftware2014/MATLAB/data.xls
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2014/10/02 11:38:00

%% Import the data
[~, ~, raw] = xlsread('/home/kilian/Dropbox/Teaching/introductiontoeconometricsoftware2014/MATLAB/data.xls','Sheet1');
raw = raw(2:end,2:end);

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
IVOLCA = data(:,1);
IVOLCH = data(:,2);
IVOLGB = data(:,3);
IVOLJP = data(:,4);
IVOLNO = data(:,5);
IVOLSE = data(:,6);
IVOLUS = data(:,7);
IVOLXM = data(:,8);

%% Clear temporary variables
clearvars data raw;